### ISSUE TITLE
Plugin freezes on loading status when broken reference

### ISSUE THREAD

**Issue by kube** [raph-amiard/sublime-typescript#8] opened 2013-02-08 13:19 UTC
Another problem is that when you make a reference to a file that doesn't exist, (by mistake, it can happen to everybody),

You have an error :

``` text
Traceback (most recent call last):
  File ".\typescript.py", line 58, in timeout_func
  File ".\typescript.py", line 85, in get_dep_text
IOError: [Errno 2] No such file or directory: u'C:\\www\\PHNXjs\\core\\imageWorkshop/imageWorkshop.ts'
```

And then the plugin freezes in loading still saying "Loading typescript plugin".
**Even if I close the file**.

Fix the _on_close()_ event would be a solution. (Issue #7)
But would it be possible to avoid the errors of broken reference links like these ?

**Comment by jasonswearingen** [comment] 2013-02-08 23:54
i would like to mention that I also experience the issue of this plugin
freezing with the "loading" text at the bottom.

props to you for articulating the actual issue to be fixed!
- Jason

**Comment by raph-amiard** [comment] 2013-03-08 15:14
Should be fixed by now, feel free to reopen if the problem is still here

**Closed as completed by raph-amiard** 2013-03-08 15:14 UTC
